-- AlterTable
ALTER TABLE `equipo` ADD COLUMN `genero` VARCHAR(191) NULL DEFAULT 'MIXTO';

-- AlterTable
ALTER TABLE `streaming` ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `views` INTEGER NOT NULL DEFAULT 0;
